
- name: Executing commands in servers
  hosts: all
  strategy: free
  tasks:

  - name: Delete result directory
    file:
      path: "/tmp/ansible_result"
      state: absent

  - name: Creates result directory
    file:
      path: "/tmp/ansible_result"
      state: directory

  - name: Creates output directory
    file:
      path: "/tmp/ansible_output"
      state: directory

  - name: Checking distribution
    copy: 
      dest: "/tmp/ansible_result/os.txt"
      content: "os_version_loc: {{ansible_distribution}}\n" 

  - name: execute the command 
    command: '{{item}}'
    register: result
    loop: "{{ q('ini', '.*', section=command_section, file='../../../master/examples.ini', re=True) }}"
    vars:
      command_section: '{{inventory_hostname}}-command'

  - name: copying the output
    copy:
      dest: "/tmp/ansible_result/'{{item.item | basename}}'.txt"
      content: "{{ item.item }}_loc: {{ item.stdout }} \n"
    loop: "{{ result.results }}"
  
  - name: assemble output into single files
    assemble:
      src: "/tmp/ansible_result"
      dest: "/tmp/ansible_output/{{inventory_hostname}}.txt"
  
  - name: fetch final output file
    fetch: 
      src: "/tmp/ansible_output/{{inventory_hostname}}.txt"
      dest: ../../../master/server_out_folder/{{inventory_hostname}}.txt
      flat: yes