#have error handling or a search functions for the search fnction

- name: Executing commands in servers
  hosts: all
  strategy: free
  tasks:

  - name: Delete result directory
    file:
      path: "/tmp/ansible_result"
      state: absent

  - name: Creates result directory
    file:
      path: "/tmp/ansible_result"
      state: directory

  - name: Creates output directory
    file:
      path: "/tmp/ansible_output"
      state: directory

   # The ini file path is hardcoded in loops and queries [Adjust accordingly]
  - name: execute the command 
    command: '{{item}}'
    register: result
    loop: "{{ q('ini', '.*', section=command_section, file='../../../MASTER/examples.ini', re=True) }}"
    vars:
      command_section: '{{inventory_hostname}}-command'

  - name: copying the output
    copy:
      dest: "/tmp/ansible_result/'{{item.item | basename}}'.txt"
      content: "{{ item.item }}_loc: {{ item.stdout }} \n"
    loop: "{{ result.results }}"
  
  - name: assemble output into single files
    assemble:
      src: "/tmp/ansible_result"
      dest: "/tmp/ansible_output/{{inventory_hostname}}.txt"
  
  #Destination path is also hardcoded. Withmy system => use relative
  - name: fetch final output file
    fetch: 
      src: "/tmp/ansible_output/{{inventory_hostname}}.txt"
      dest: /home/rithvik_ravilla/server_automate/MASTER/server_out_folder/{{inventory_hostname}}.txt
      flat: yes