- name: Executing commands in servers
  hosts: all
  strategy: free
  tasks:

  - name: Executing shell command
    ansible.builtin.command: "{{ shell_command }}"
    register: result
    changed_when: false

  - name: Creating output file
    ansible.builtin.copy:
      dest: "/tmp/ansible_result/'{{ shell_command }}'_shell.txt"
      content: "{{ shell_command }}_loc: {{ result.stdout }}\n"
      mode: "0644"

  - name: Fetch output file
    ansible.builtin.fetch:
      src: "/tmp/ansible_result/'{{ shell_command }}'_shell.txt"
      dest: ../../../master/shell_out_folder/{{ inventory_hostname }}.txt
      flat: true
